module.exports = [
  {
    id: 1,
    name: "Almond Toe Court Shoe",
    desc: "Patent black",
    category: "Women's Footwear",
    price: 99.00,
    quantity: 5,
    img: "img/almondtoecourtshoe.jpg",
  },
  {
    id: 2,
    name: "Suede Shoes",
    desc: "Blue",
    category: "Women's Footwear",
    price: 42.00,
    quantity: 4,
    img: "img/bluesuedeshoe.jpg",
  },
  {
    id: 3,
    name: "Leather Driver Saddle Loafers",
    desc: "Tan",
    category: "Men's Footwear",
    price: 34.00,
    quantity: 12,
    img: "img/tanloafers.jpg",
  },
  {
    id: 4,
    name: "Red Flip-Flops",
    desc: "Red",
    category: "Men's Footwear",
    price: 19.00,
    quantity: 6,
    img: "img/redflipflop.jpg",
  },
  {
    id: 5,
    name: "Blue Flip-Flops",
    desc: "Blue",
    category: "Men's Footwear",
    price: 19.00,
    quantity: 0,
    img: "img/blueflipflop/jpg",
  },
  {
    id: 6,
    name: "Gold Button Cardigan",
    desc: "Black",
    category: "Women's Casualwear",
    price: 167.00,
    quantity: 6,
    img: "img/goldbuttoncardigan.jpeg",
  },
  {
    id: 7,
    name: "Cotton Shorts",
    desc: "Medium, red",
    category: "Women's Casualwear",
    price: 30.00,
    quantity: 5,
    img: "img/redcottonshorts.jpg",
  },
  {
    id: 8,
    name: "Grey Fine Stripe Short Sleeve Shirt",
    desc: "Grey",
    category: "Men's Casualwear",
    price: 49.99,
    quantity: 9,
    img: "img/greyshirt.jpg",
  },
  {
    id: 9,
    name: "Green Fine Strip Short Sleeve Shirt",
    desc: "Green",
    category: "Men's Casualwear",
    price: 39.99 ,
    quantity: 3,
    img: "img/greenshirt.jpg",
  },
  {
    id: 10,
    name: "Sharkskin Waistcoat",
    desc: "Charcoal",
    category: "Men's Formalwear",
    price: 75.00,
    quantity: 2,
    img: "img/sharkskinwaistcoat.jpg",
  },
  {
    id: 11,
    name: "Lightweight Patch Pocket Blazer",
    desc: "Deer",
    category: "Men's Formalwear",
    price: 175.50,
    quantity: 1,
    img: "img/patchpocketblazer.jpeg",
  },
  {
    id: 12,
    name: "Bird Print Dress",
    desc: "Black",
    category: "Women's Formalwear",
    price: 270.00,
    quantity: 10,
    img: "img/birdprintdress.jpg",
  },
  {
    id: 13,
    name: "Mid Twist Cut-Out Dress",
    desc: "Pink",
    category: "Women's Formalwear",
    price: 540.00,
    quantity: 5,
    img: "img/midtwistcutoutdress.jpeg",
  }
]
